# Setup zookeeper on zookeeper ensemble
- name: Add user zookeeper
  user:
    name: zookeeper
- name: Download and Unarchive Zookeeper
  unarchive:
    src: http://www-us.apache.org/dist/zookeeper/zookeeper-{{ ZOOKEEPER_VERSION }}/zookeeper-{{ ZOOKEEPER_VERSION }}.tar.gz
    dest: /opt
    remote_src: yes
    owner: zookeeper
    group: zookeeper
    mode: 0755
- name: create softlink for zookeeper base dir
  file:
    src: /opt/zookeeper-{{ ZOOKEEPER_VERSION }}
    path: /opt/zookeeper
    state: link
    owner: zookeeper
    group: zookeeper
- name: copy zoo.cfg and log4j.properties
  synchronize:
    src: "{{ base_dir }}/files/opt/zookeeper/conf"
    dest: /opt/zookeeper
- name: change permissions on /opt/kafka/config
  file:
    path: /opt/zookeeper/conf
    recurse: yes
    owner: zookeeper
    group: zookeeper
    mode: 0755
- name: Create data directory
  file:
    path: "{{ item }}"
    state: directory
    owner: zookeeper
    group: zookeeper
    mode: 0755
  loop:
    - /data1/zookeeper
    - /var/log/zookeeper
