---
# Perform common tasks on all nodes
- hosts: all
  tags: ['common', 'install']
  roles:
    - role: common
  become: true

# Setup zookeeper on zookeeper ensemble
- hosts: ensemble
  vars:
    ZOOKEEPER_VERSION: 3.4.12
  tags: ['ensemble', 'install', 'zoo_upgrade'] 
  roles:
    - role: zookeeper
  become: true

# Setup kafka brokers
- hosts: brokers
  vars:
    SCALA_VERSION: 2.11
    KAFKA_VERSION: 2.0.0
  tags: ['kafka', 'install', 'kafka_upgrade']
  roles:
    - role: kafka
  become: true

# Setup kafka client
- hosts: gateways
  vars:
    SCALA_VERSION: 2.11
    KAFKA_VERSION: 2.0.0
  tags: ['kafka', 'install', 'kafka_upgrade']
  roles:
    - role: client
  become: true
