# Setup kafka brokers
- name: Add user kafka
  user:
    name: kafka
- name: create directory for kafka data with owner as kafka
  file:
    path: /data1/kafka-logs
    owner: kafka
    group: kafka
    state: directory
- name: create directory for kafka data with owner as kafka
  file:
    path: /data2/kafka-logs
    owner: kafka
    group: kafka
    state: directory
- name: Download Kafka Tar
  unarchive:
    src: http://www-us.apache.org/dist/kafka/{{ KAFKA_VERSION }}/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}.tgz
    dest: /opt
    remote_src: yes
    owner: kafka
    group: kafka
    mode: 0755
- name: create softlink for kafka base dir
  file:
    src: /opt/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}
    path: /opt/kafka
    state: link
    owner: kafka
    group: kafka
- name: Create Kafka log directory
  file:
    path: /var/log/kafka
    state: directory
    owner: kafka
    group: kafka
    mode: 0755
- name: copy server.properties
  synchronize:
    src: /home/training/kafka-ansible/single-playbook/files/opt/kafka/config
    dest: /opt/kafka
- name: change permissions on kafka config files
  file:
    path: /opt/kafka/config
    recurse: yes
    owner: kafka
    group: kafka
