# Setup kafka client
- name: Add user kafka
  user:
    name: kafka
- name: Download Kafka Tar
  unarchive:
    src: http://www-us.apache.org/dist/kafka/{{ KAFKA_VERSION }}/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}.tgz
    dest: /opt
    remote_src: yes
    owner: kafka
    group: kafka
    mode: 0755
- name: create softlink for kafka base dir
  file:
    src: /opt/kafka_{{ SCALA_VERSION }}-{{ KAFKA_VERSION }}
    path: /opt/kafka
    state: link
    owner: kafka
    group: kafka
